package com.example.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.local.SignalEntity
import com.example.data.model.Signal
import com.example.data.model.SignalSeverity
import com.example.ui.components.SignalItemCard
import com.example.ui.theme.*

@Composable
fun SignalsScreen(
    signals: List<SignalEntity>,
    modifier: Modifier = Modifier
) {
    var selectedFilter by remember { mutableStateOf<String?>("ALL") }

    val filtered = remember(signals, selectedFilter) {
        if (selectedFilter == "ALL" || selectedFilter == null) {
            signals
        } else {
            signals.filter { it.severity.equals(selectedFilter, ignoreCase = true) }
        }
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(DeskDarkBackground)
    ) {
        // Filter bar
        LazyRow(
            modifier = Modifier
                .fillMaxWidth()
                .background(DeskSurface)
                .padding(horizontal = 14.dp, vertical = 8.dp),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            val filters = listOf("ALL", "BULLISH", "BEARISH", "WARNING", "INFO")
            items(filters) { f ->
                val isSelected = selectedFilter == f
                Box(
                    modifier = Modifier
                        .clip(RoundedCornerShape(6.dp))
                        .background(if (isSelected) CyanPrimary else DeskSurfaceVariant)
                        .clickable { selectedFilter = f }
                        .padding(horizontal = 10.dp, vertical = 6.dp)
                ) {
                    Text(
                        text = f,
                        color = if (isSelected) DeskDarkBackground else TextSecondary,
                        fontSize = 10.sp,
                        fontWeight = FontWeight.Bold,
                        fontFamily = FontFamily.Monospace
                    )
                }
            }
        }

        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = 14.dp),
            contentPadding = PaddingValues(vertical = 12.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp)
        ) {
            if (filtered.isEmpty()) {
                item {
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(vertical = 60.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        Column(horizontalAlignment = Alignment.CenterHorizontally) {
                            Text(
                                text = "No active signals",
                                color = TextMuted,
                                fontSize = 13.sp,
                                fontFamily = FontFamily.Monospace
                            )
                            Spacer(modifier = Modifier.height(4.dp))
                            Text(
                                text = "Signals are only generated by verified agent execution or real price alerts.",
                                color = TextMuted,
                                fontSize = 10.sp,
                                fontFamily = FontFamily.Monospace
                            )
                        }
                    }
                }
            } else {
                items(filtered) { s ->
                    val sev = try {
                        SignalSeverity.valueOf(s.severity)
                    } catch (e: Exception) {
                        SignalSeverity.INFO
                    }
                    SignalItemCard(
                        signal = Signal(
                            id = s.id,
                            timestamp = s.timestamp,
                            symbol = s.symbol,
                            agent = s.agent,
                            title = s.title,
                            detail = s.detail,
                            severity = sev,
                            source = s.source,
                            verified = s.verified
                        )
                    )
                }
            }
        }
    }
}
