package com.example

import com.example.ai.agents.MarketDataAgent
import com.example.ai.agents.TechnicalCalculations
import com.example.ai.orchestrator.AgentOrchestrator
import com.example.ai.provider.LocalProvider
import com.example.ai.provider.ProviderConfig
import com.example.ai.provider.ProviderType
import com.example.data.model.*
import com.example.data.remote.MarketDataService
import com.example.data.remote.NewsIntelligenceService
import kotlinx.coroutines.runBlocking
import org.junit.Assert.*
import org.junit.Test

class TradingDeskUnitTest {

    @Test
    fun testMarketDataNullDisplaysEmDash() {
        val unavailable = MarketData(
            symbol = "XYZ",
            name = "Unknown Corp",
            price = null,
            change = null,
            changePercent = null,
            high = null,
            low = null,
            open = null,
            previousClose = null,
            volume = null,
            source = "Direct",
            status = MarketDataStatus.UNAVAILABLE
        )

        // Mandatory prompt test:
        // When market API returns null: Expected UI: —, NOT 0, N/A price generated by AI, random number, previous value marked as live
        assertEquals("—", unavailable.formattedPrice)
        assertEquals("—", unavailable.formattedChange)
        assertFalse(unavailable.isDemo)
    }

    @Test
    fun testMarketDataAgentHandlesUnavailableGracefully() = runBlocking {
        val agent = MarketDataAgent()
        val result = agent.run(
            symbol = "FAKE",
            marketData = null,
            candles = emptyList(),
            news = emptyList()
        )

        assertEquals("market_data", result.agent)
        assertEquals("unavailable", result.status)
        assertEquals("—", result.calculations["price"])
        assertTrue(result.observations.any { it.contains("DATA UNAVAILABLE") })
        assertTrue(result.errors.isNotEmpty())
    }

    @Test
    fun testTechnicalCalculationSMA() {
        val candles = listOf(
            Candle(1000, 10.0, 12.0, 9.0, 10.0, 100.0),
            Candle(2000, 10.0, 15.0, 9.0, 20.0, 100.0),
            Candle(3000, 20.0, 35.0, 19.0, 30.0, 100.0)
        )
        val sma = TechnicalCalculations.calculateSMA(candles, 3)
        assertNotNull(sma)
        assertEquals(20.0, sma!!, 0.001)
    }

    @Test
    fun testTechnicalCalculationRSI() {
        // Create 20 ascending candles -> RSI should be high (> 70)
        val candles = (1..20).map { i ->
            Candle(i * 1000L, i.toDouble(), i.toDouble() + 1.0, i.toDouble() - 0.5, i.toDouble() + 0.5, 50.0)
        }
        val rsi = TechnicalCalculations.calculateRSI(candles, 14)
        assertNotNull(rsi)
        assertTrue("RSI should be high on strictly rising prices: $rsi", rsi!! > 70.0)
    }

    @Test
    fun testTechnicalSupportResistancePivots() {
        val candles = listOf(
            Candle(1000, 100.0, 110.0, 90.0, 105.0, 1000.0)
        )
        val sr = TechnicalCalculations.calculateSupportResistance(candles)
        assertNotNull(sr)
        // Pivot = (110 + 90 + 105) / 3 = 305 / 3 = 101.667
        assertEquals(101.667, sr!!.pivot, 0.01)
        // Resistance = (2 * pivot) - low = 203.333 - 90 = 113.333
        assertEquals(113.333, sr.resistance, 0.01)
        // Support = (2 * pivot) - high = 203.333 - 110 = 93.333
        assertEquals(93.333, sr.support, 0.01)
    }

    @Test
    fun testAgentOrchestratorRouting() {
        val orchestrator = AgentOrchestrator(
            MarketDataService(),
            NewsIntelligenceService(),
            null
        )

        // 1. Price query -> Market data only
        val priceRoutes = orchestrator.routeAgents("What is the current BTC price?")
        assertEquals(1, priceRoutes.size)
        assertEquals(AgentType.MARKET_DATA, priceRoutes[0])

        // 2. "Why is it moving" -> Market + News + Sentiment
        val whyRoutes = orchestrator.routeAgents("Why is BTC moving today?")
        assertTrue(whyRoutes.contains(AgentType.MARKET_DATA))
        assertTrue(whyRoutes.contains(AgentType.NEWS))
        assertTrue(whyRoutes.contains(AgentType.SENTIMENT))
        assertFalse(whyRoutes.contains(AgentType.BULL_RESEARCHER))

        // 3. Complete analysis -> all 9 agents
        val fullRoutes = orchestrator.routeAgents("Give me a complete NVDA analysis.")
        assertEquals(9, fullRoutes.size)

        // Symbol extraction test
        assertEquals("BTC", orchestrator.extractSymbol("What's happening with Bitcoin?"))
        assertEquals("NVDA", orchestrator.extractSymbol("Analyze NVDA today"))
        assertEquals("ETH", orchestrator.extractSymbol("Check ETH levels"))
    }

    @Test
    fun testLocalAIProvider() = runBlocking {
        val provider = LocalProvider()
        val health = provider.healthCheck()
        assertTrue(health.isConnected)

        val result = provider.generate("Analyze NVDA", null)
        assertTrue(result.isSuccess)
        assertTrue(result.getOrThrow().contains("LOCAL INTELLIGENCE SYNTHESIS ENGINE"))
    }

    @Test
    fun testDemoModeSeparation() = runBlocking {
        val service = MarketDataService()
        service.isDemoMode = true
        val demoQuote = service.getQuote("BTC")
        assertTrue(demoQuote.isDemo)
        assertEquals("DEMO SIMULATOR", demoQuote.source)

        service.isDemoMode = false
        // Live mode is not demo
        assertFalse(service.isDemoMode)
    }
}
